### ISSUE TITLE
Image is not being displayed in the list

### ISSUE THREAD

**Issue by utkarsh006** [utkarsh006/Android-Pagination#1]

**Comment by TharunBalaji2004** [comment]
Hey there @utkarsh006, the architecture you have used to build and usage of Pagination3 is really awesome. After spending lot of time, in Logging and figuring out why the image doesn't load.... I found that the BeerCard was rendering `imgUrl` as NULL. 

Then I checked whether INTERNET permission was allowed and checked the API and ROOM DB layer code. Seems like everything is working fine and I found that the DB was storing NULL under `imgUrl` columns for all the data.

After figuring out the issue, I tried hitting the API and carefully analyzed the payload fields. To my surprise, I found that the API was returning the image URL as `image_url` but inside the `BeerDto` it was specified as `img_url` 😅

| API response payload | BeerDto data class |
| :-------: | :---------: |
| ![image](https://github.com/utkarsh006/Android-Pagination/assets/95350584/17a85182-f3d2-4381-86d9-c445717b5df0) | ![image](https://github.com/utkarsh006/Android-Pagination/assets/95350584/a68b1c1f-7cb9-40b0-8e32-e92769ab8b64) |

After rectifying the issue of variable name, now the beer images are visible! 💯


https://github.com/utkarsh006/Android-Pagination/assets/95350584/f8bb0fff-a069-4876-a35f-c01970cdcfe2

**Comment by utkarsh006** [comment]
@TharunBalaji2004 Thanks for noticing this man! Good work as always
